FROM golang:1.24-bookworm AS builder

WORKDIR /app

COPY . .

RUN cd cmd/route-service && go build -o /route-service

FROM gcr.io/distroless/base-debian11

COPY --from=builder /route-service /

ENTRYPOINT ["/route-service"]

